# Generated by Django 4.1.7 on 2023-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='town',
            field=models.CharField(default='Minsk', max_length=250),
        ),
    ]
